version: '3.8'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: simple-queue-user
      POSTGRES_PASSWORD: xa35!ZxX(@A
      POSTGRES_DB: simple-queue
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network
    deploy:
      mode: replicated
      replicas: 2        # Deploy 2 replicas across master and worker
      placement:
        max_replicas_per_node: 1  # Ensures distribution across nodes
    ports:
      - 5432:5432

  java-backend:
    image: acr02demo.azurecr.io/java-backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/simple-queue
      - SPRING_DATASOURCE_USERNAME=simple-queue-user
      - SPRING_DATASOURCE_PASSWORD=xa35!ZxX(@A
    networks:
      - backend-network
    deploy:
      mode: replicated
      replicas: 2        # Deploy 2 replicas of the Java backend across master and worker
      placement:
        max_replicas_per_node: 1  # Ensures distribution across nodes
    ports:
      - 8088:8088

  angular-frontend:
    image: acr02demo.azurecr.io/angular-frontend:latest  # Replace with your actual image name and tag
    environment:
      - NODE_ENV=production
    networks:
      - backend-network  # If needed to communicate with the backend
    #  - frontend-network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
    ports:
      - 4200:4200  # Frontend exposed on port 8085

volumes:
  db-data:  # Volume for persistent database storage

networks:
  backend-network:
    driver: overlay
  frontend-network:
    driver: overlay
