version: '3.8'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: simple-queue-user
      POSTGRES_PASSWORD: xa35!ZxX(@A
      POSTGRES_DB: simple-queue
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker  # Ensure deployment only on worker node
    ports:
      - 5432:5432

  java-backend:
    image: acr02demo.azurecr.io/java-backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/simple-queue
      - SPRING_DATASOURCE_USERNAME=simple-queue-user
      - SPRING_DATASOURCE_PASSWORD=xa35!ZxX(@A
    networks:
      - backend-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker  # Ensure deployment only on worker node
      restart_policy:
        condition: on-failure
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
    ports:
      - 8088:8080

  angular-frontend:
    image: acr02demo.azurecr.io/angular-frontend:latest
    environment:
      - NODE_ENV=production
    networks:
      - backend-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker  # Ensure deployment only on worker node
    ports:
      - 4200:4200  # Frontend exposed on port 4200

volumes:
  db-data:

networks:
  backend-network:
    driver: overlay
